stages:
  - build_backend
  - lint_frontend
  - build_frontend

build-backend:
  stage: build_backend
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination backend-app:latest

lint-frontend:
  stage: lint_frontend
  image: node:22
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run lint

build-frontend:
  stage: build_frontend
  image: node:22
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build