spring.datasource.url=jdbc:sqlite:devoir2.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Hibernate settings
spring.jpa.show-sql=true
# SQLite doesn't support sophisticated connection pooling like Hikari default settings
# These limits help prevent "Database is locked" errors
spring.datasource.hikari.maximum-pool-size=1
